# Generated by Django 4.1.7 on 2023-03-31 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalog_set', to='core.devicelog', verbose_name='Log')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datamodel', verbose_name='Modelo')),
            ],
        ),
    ]
