# Generated by Django 4.1.9 on 2023-06-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('is_researcher', models.BooleanField(default=False, verbose_name='Pesquisador')),
                ('research_institution', models.CharField(max_length=100, verbose_name='Instituição de pesquisa')),
                ('reasearch_area', models.CharField(max_length=150, verbose_name='Área de pesquisa')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('projects', models.ManyToManyField(blank=True, related_name='users', to='core.project', verbose_name='Projetos (como bolsista)')),
            ],
        ),
    ]
